deployment:
  restartPolicy: Always
  app_name: overlap-checker
  labels:
    app: overlap-checker
    role: API-endpoint
  replicaCount: 3
  containerPort: 8000

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  image:
    repository: "514005485562.dkr.ecr.us-east-1.amazonaws.com/overlap-checker"
    pullPolicy: IfNotPresent
    tag: "92003444f059741d6f018f79b299ea0ceedf3a49-7"

  env:
    - name: ENVIRONMENT
      value: "production"

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

service:
  svc_name: overlap-checker-svc
  type: ClusterIP
  port: 80
  targetPort: 8000
  selector:
    app: overlap-checker
